system_config:
  F: [[1, 0.1], [0, 1]]
  G: [[0], [1]]
  H: [[1, 0]]
  Q_true: [0.0, 0.0]
  R_true: 0.5
  x0: [0, 1]
  P0: [[1, 0], [0, 1]]
  u: 0
  steps: 100
  nx: 2
  nz: 1
  data_seed: 42

optimization_config:
  param_bounds:
    Q: [0.01, 1.0]
    R: [0.1, 1.0]
  n_calls: 30
  opt_seed: 42
